name: Run npm command

on:
  workflow_call:
    inputs:
      working-directory:
        default: "."
        type: string
      run:
        required: true
        type: string

jobs:
  npm-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: npm ci --no-progress

      - name: Run task
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.run }}
